import { Asset } from "@/types/asset";
import { columns } from "./columns";
import { DataTable } from "@/components/data-table";

const DashBoard = () => {
  const assets: Asset[] = [
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 1,
      assetType: "Laptop",
      assetId: "30258789",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 2,
      assetType: "Printer",
      assetId: "40258901",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 3,
      assetType: "Projector",
      assetId: "50258967",
      category: "Office Equipment",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 4,
      assetType: "Desktop",
      assetId: "60258944",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Active",
    },
    {
      sl: 5,
      assetType: "Scanner",
      assetId: "70258799",
      category: "Office Equipment",
      department: "IT Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 6,
      assetType: "Tablet",
      assetId: "80258745",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 7,
      assetType: "Laptop",
      assetId: "30258790",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
    {
      sl: 8,
      assetType: "Projector",
      assetId: "50258968",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 9,
      assetType: "Desktop",
      assetId: "60258945",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Dhanmondi Dhaka",
      floor: "4th/CC",
      status: "Inactive",
    },
    {
      sl: 10,
      assetType: "Printer",
      assetId: "40258902",
      category: "Electronic Device",
      department: "Admin Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Active",
    },
    {
      sl: 11,
      assetType: "Laptop",
      assetId: "30258791",
      category: "Electronic Device",
      department: "Tech Department",
      branch: "Mirpur Dhaka",
      floor: "1st/DD",
      status: "Active",
    },
    {
      sl: 12,
      assetType: "Tablet",
      assetId: "80258746",
      category: "Electronic Device",
      department: "HR Department",
      branch: "Uttara Dhaka",
      floor: "3rd/BD",
      status: "Inactive",
    },
    {
      sl: 13,
      assetType: "Scanner",
      assetId: "70258800",
      category: "Office Equipment",
      department: "Sales Department",
      branch: "Motijheel Dhaka",
      floor: "5th/CA",
      status: "Active",
    },
    {
      sl: 14,
      assetType: "Projector",
      assetId: "50258969",
      category: "Office Equipment",
      department: "Admin Department",
      branch: "Banani Dhaka",
      floor: "2nd/AB",
      status: "Active",
    },
    {
      sl: 15,
      assetType: "Desktop",
      assetId: "60258946",
      category: "Electronic Device",
      department: "Finance Department",
      branch: "Gulshan Dhaka",
      floor: "6th/EF",
      status: "Inactive",
    },
  ];

  return (
    <div>
      {/* <div className="flex justify-between items-center mb-4">
        <input
          type="text"
          placeholder="Search assets items"
          className="border rounded-md px-4 py-2"
        />
        <div className="flex space-x-2">
          <button className="border rounded-md px-4 py-2">Export</button>
          <button className="border rounded-md px-4 py-2">Audit</button>
          <button className="border rounded-md px-4 py-2">Print</button>
          <select className="border rounded-md px-4 py-2">
            <option value="all">All Assets</option>
            <option value="recent">Recently Added</option>
          </select>
          <button className="bg-green-500 text-white rounded-md px-4 py-2">
            Add Asset
          </button>
        </div>
      </div> */}

      <DataTable columns={columns} data={assets} />
    </div>
  );
};

export default DashBoard;
